version: '3.7'

services:
  db:
    image: mysql:5.7.35
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123 
      MYSQL_DATABASE: test 
      MYSQL_USER: test 
      MYSQL_PASSWORD: test123 

  jupyter:
    image: jupyter/base-notebook
    ports:
      - 8888:8888
