---
title: "Academatica Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(ggplot2)
library(formattable)
```

```{r datasets}
vides <- read_csv("data/academatica_videos.csv")
metadata <- read_csv("data/academatica_videos_metadata.csv")
stats <- read_csv("data/academatica_video_stats.csv")
```

```{r metricas}
metricas <- stats %>%
  summarise(total_views = sum(viewCount),
            total_likes = sum(likeCount),
            total_dislikes = sum(dislikeCount),
            total_favorite = sum(favoriteCount),
            total_comment = sum(commentCount)
            )
```



# Metricas {data-icon=fa-ruler}
##
### Reproducciones
```{r}
valueBox(metricas$total_views %>% formattable::comma(digits = 0), 
         icon="fa-eye",
         color="info")
```


### Likes
```{r}
valueBox(metricas$total_likes %>% formattable::comma(digits = 0), 
         icon="fa-thumbs-up",
         color="success")
```

### Comentarios

```{r}
valueBox(metricas$total_comment %>% formattable::comma(digits = 0), 
         icon="fa-comments",
         color="warning")
```

##
### Likes rate

```{r}
like_rate = metricas$total_likes/(metricas$total_likes + metricas$total_dislikes)
like_rate = round(like_rate * 100, 0)

gauge(like_rate, min=0, max=100, symbol = '%', 
      gaugeSectors(success = c(80, 100),
                   warning = c(40, 79),
                   danger = c(0, 39)))

```

###


# Data

